---
- name: Installing necessities for master-server
  hosts: server1
  become: yes


  tasks:
  - name: update system
    apt:
      update_cache: yes
  
  - name: install Nagios Client NRPE
    apt:
      name: nagios-nrpe-server 
      state: present

  - name: install nagios Client NRPR plugins
    apt:
      name: nagios-plugins
      state: present


  - name: install rsyslog
    apt:
      name: rsyslog
      state: present

  - name: install apache2
    apt:
      name: apache2
      state: present
      
  - name: install mysql
    apt:
      name: mysql-server
      state: present

  - name: install php
    apt:
      name: php
      state: present
     
  - name: start apache2 service
    service:
      name: apache2
      state: started
      enabled: true

  - name: start mysql service
    service:
      name: mysql
      state: started
      enabled: true
      
  - name: start mysql service
    service:
      name: rsyslog
      state: started
      enabled: true